
import __ASTRO_IMAGE_IMPORT_ZXEfgt from "../../assets/vulkan-logo.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZbLT0W from "../../../assets/Setup/mingw-w64.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md";
import __ASTRO_IMAGE_IMPORT_ZBXWy9 from "../../../assets/Setup/bin_folder.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md";
import __ASTRO_IMAGE_IMPORT_2He4U from "../../../assets/Setup/env_search.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md";
import __ASTRO_IMAGE_IMPORT_Y1ir8 from "../../../assets/Setup/select_env_vars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md";
import __ASTRO_IMAGE_IMPORT_Z1zKSRV from "../../../assets/Setup/paste_dir.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md";
import __ASTRO_IMAGE_IMPORT_19JJea from "../../../assets/Setup/vk_cube.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md";
export default new Map([["../../assets/vulkan-logo.svg?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Findex.mdx", __ASTRO_IMAGE_IMPORT_ZXEfgt], ["../../../assets/Setup/mingw-w64.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md", __ASTRO_IMAGE_IMPORT_ZbLT0W], ["../../../assets/Setup/bin_folder.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md", __ASTRO_IMAGE_IMPORT_ZBXWy9], ["../../../assets/Setup/env_search.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md", __ASTRO_IMAGE_IMPORT_2He4U], ["../../../assets/Setup/select_env_vars.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md", __ASTRO_IMAGE_IMPORT_Y1ir8], ["../../../assets/Setup/paste_dir.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md", __ASTRO_IMAGE_IMPORT_Z1zKSRV], ["../../../assets/Setup/vk_cube.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fdocs%2Fgetting_started%2Fenv_setup.md", __ASTRO_IMAGE_IMPORT_19JJea]]);
		